document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("	<title></title>");
document.writeln("	<link rel=\'stylesheet\' type=\'text/css\' href=\'css/conn.css\'>");
document.writeln("	<meta charset=\'utf-8\'>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("	    	<div id=\'header\' class=\'pc-head\'>");
document.writeln("	<div class=\'top\'>");
document.writeln("		<div class=\'t-left\'>");
document.writeln("			<a href=\'###\'><p>© THE FINAL RIGHT OF INTERPRETATION IS OWNED BY THE  YOUYAN GRO</p></a>");
document.writeln("		</div>");
document.writeln("		<div class=\'t-right\'>");
document.writeln("			<a href=\'###\'>");
document.writeln("			<div class=\'wxlogo\'>");
document.writeln("				<img src=\'./images/wxlogo.png\'>");
document.writeln("				<P>官方微信</P>");
document.writeln("				<div class=\'ycewm\'>");
document.writeln("					<img src=\'./images/ycewm.jpg\' width=\'150px\'>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			</a>");
document.writeln("			<a href=\'https://weibo.com/p/1006065062440955/home?from=page_100606&mod=TAB&is_hot=1#place\' target=\' _blank\'>");
document.writeln("			<div class=\'wxlogo xllogo\'>");
document.writeln("				<img src=\'./images/xllogo.png\'>");
document.writeln("				<P>官方微博</P>");
document.writeln("				<!-- <div class=\'xlewm\'>");
document.writeln("					<img src=\'./images/xlewm.jpg\' width=\'140px\'>");
document.writeln("				</div> -->");
document.writeln("			</div>");
document.writeln("			</a>");
document.writeln("						<!-- 这里是搜索 -->");
document.writeln("			<!-- <a href=\'###\'>");
document.writeln("");
document.writeln("			<div class=\'wxlogo ssl\'>");
document.writeln("				<input type=\'text\' id=\'search-orange\' />");
document.writeln("			</div>");
document.writeln("			</a> -->");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<div class=\'column\'>");
document.writeln("		<div class=\'logo\'>");
document.writeln("			<a href=\'/\'>");
document.writeln("				<img src=\'./images/logo.png\'alt=\'eceiro 医采品牌官方网站\'>");
document.writeln("			</a>");
document.writeln("		</div>");
document.writeln("		<div class=\'nav\'>");
document.writeln("			<ul>");
document.writeln("				<li>");
document.writeln("					<a href=\'/\' target=\'_top\'>品牌首页</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'javascript:void(0).html\' target=\'_top\'>明星产品</a>");
document.writeln("						<ul class=\'e_nav\'>");
document.writeln("							<li class=\'e1\'>");
document.writeln("								<a href=\'javascript:void(0)\' target=\'_top\'>彩妆</a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'pdlczmh.html\'  target=\'_top\'>潘多拉彩妆魔盒</a></li>");
// document.writeln("										<li><a href=\'lgycsm.html\'  target=\'_top\'>流光耀彩水蜜唇釉</a></li>");
// document.writeln("										<li><a href=\'ljhcmr.html\'  target=\'_top\'>琉金幻彩魅人口红</a></li>");
document.writeln("										<li><a href=\'mddskh.html\'  target=\'_top\'>摩登都市魅色口红</a></li>");
document.writeln("										<li><a href=\'ssmf.html\'  target=\'_top\'>轻雾丝盈三色蜜粉</a></li>");
document.writeln("									</ul>");
document.writeln("							</li>");
document.writeln("							<li class=\'e2\'>");
document.writeln("								<a href=\'javascript:void(0)\' target=\'_top\'>护肤</a>");
document.writeln("									<ul>");
document.writeln("										<li class=\'hfhz\'> ");
document.writeln("											<a href=\'jhth.html\'  target=\'_top\'>肌活自律循环套盒></a>");
document.writeln("												<ul>");
document.writeln("													<li><a href=\'jhjmr.html\'  target=\'_top\'>肌活净透保湿洁面乳</a></li>");
document.writeln("													<li><a href=\'jhjks.html\'  target=\'_top\'>肌活自律循环健康水</a></li>");
document.writeln("													<li><a href=\'jhxfr.html\'  target=\'_top\'>肌活自律循环修护乳</a></li>");
document.writeln("													<li><a href=\'jhzys.html\'  target=\'_top\'>肌活自律循环滋养霜</a></li>");
document.writeln("												</ul>");
document.writeln("										</li>");
document.writeln("										<li class=\'hfhz\'> ");
document.writeln("											<a href=\'sghfth.html\'  target=\'_top\'>多肽奢宠水光护肤套盒></a>");
document.writeln("												<ul>");
document.writeln("													<li><a href=\'jyjmr.html\'  target=\'_top\'>多肽焕采净颜洁面乳</a></li>");
document.writeln("													<li><a href=\'xhsjs.html\'  target=\'_top\'>多肽润养修护生机水</a></li>");
document.writeln("													<li><a href=\'xhsgr.html\'  target=\'_top\'>多肽活颜修护水光乳</a></li>");
document.writeln("													<li><a href=\'ryyjh.html\'  target=\'_top\'>多肽修护日夜眼精华</a></li>");
document.writeln("												</ul>");
document.writeln("										</li>");
document.writeln("										<li><a href=\'wxqdbbs.html\' target=\'_top\'>瓷妆无瑕气垫BB霜</a></li>");
document.writeln("										<li><a href=\'mjxhcsmm.html\'  target=\'_top\'>多肽密集修护蚕丝面膜</a></li>");
document.writeln("										<li><a href=\'swxwqcmm.html\'  target=\'_top\'>多肽生物纤维青春面膜</a></li>");
document.writeln("										<li><a href=\'jhpw.html\'  target=\'_top\'>水感清透防护喷雾</a></li>");
document.writeln("										<li><a href=\'shbspw.html\'  target=\'_top\'>多效舒缓保湿喷雾</a></li>");
document.writeln("										<li><a href=\'qcdgy.html\'  target=\'_top\'>多肽青春定格原液</a></li>");
document.writeln("										<li><a href=\'xfsgmx.html\'  target=\'_top\'>多肽修复水光面霜</a></li>");
document.writeln("										<li><a href=\'xjhyglfhx.html\'  target=\'_top\'>新肌焕颜隔离防护霜</a></li>");
document.writeln("									</ul>");
document.writeln("							</li>");
document.writeln("							<li class=\'e3\'>");
document.writeln("								<a href=\'javascript:void(0)\' target=\'_top\'>洗护</a>");
document.writeln("									<ul>");
document.writeln("");
document.writeln("										<li><a href=\'rhhfm.html\'  target=\'_top\'>奢美丝滑养护发膜</a></li>");
document.writeln("										<li><a href=\'jhstr.html\'  target=\'_top\'>悦享美肌香氛身体乳</a></li>");
document.writeln("										<li><a href=\'knsgz.html\'  target=\'_top\'>男士酷能醒肤手工皂</a></li>");
document.writeln("										<li><a href=\'mcsgz.html\'  target=\'_top\'>男士抹茶控油手工皂</a></li>");
document.writeln("										<li><a href=\'sgjtsyxzs.html\'  target=\'_top\'>水感净透舒颜卸妆水</a></li>");
document.writeln("									</ul>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'javascript:void(0)\' target=\'_top\'>德国美肤</a>");
document.writeln("						<ul class=\'e_nav\'>");
document.writeln("							<li><a href=\'qsjksl.html\' target=\'_top\'>轻熟肌抗衰老</a></li>");
document.writeln("							<li><a href=\'dghfzx.html\' target=\'_top\'>德国护肤哲学</a></li>");
document.writeln("						</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'javascript:void(0)\' target=\'_top\'>探索医采</a>");
document.writeln("						<ul class=\'e_nav\'>");
document.writeln("							<li><a href=\'ycsys.html\' target=\'_top\'>医采实验室</a></li>");
document.writeln("							<li><a href=\'ppgc.html\' target=\'_top\'>品牌工厂</a></li>");
document.writeln("						</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'javascript:void(0)\' target=\'_top\'>品牌故事</a>");
document.writeln("						<ul class=\'e_nav\'>");
document.writeln("							<li><a href=\'csrw.html\' target=\'_top\'>创始人物</a></li>");
document.writeln("							<li><a href=\'ppln.html\' target=\'_top\'>品牌理念</a></li>");
document.writeln("						</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'javascript:void(0)\' target=\'_top\'>媒体报道</a>");
document.writeln("						<ul class=\'e_nav\'>");
document.writeln("							<li><a href=\'xinwendongtai/index.html\' target=\'_top\'>品牌动态</a></li>");
document.writeln("						</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'javascript:void(0)\' target=\'_top\'>加入我们</a>");
document.writeln("						<ul class=\'e_nav\'>");
document.writeln("							<li><a href=\'pphz.html\' target=\'_top\'>品牌合作</a></li>");
document.writeln("							<li><a href=\'jxcx.html\' target=\'_top\'>经销查询</a></li>");
document.writeln("						</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'javascript:void(0)\' target=\'_top\'>售后服务</a>");
document.writeln("						<ul class=\'e_nav\'>");
document.writeln("							<li><a href=\'fwcx.html\' target=\'_top\'>防伪查询</a></li>");
document.writeln("							<li><a href=\'khfw.html\' target=\'_top\'>客户服务</a></li>");
document.writeln("						</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'javascript:void(0)\' target=\'_top\'>关于我们</a>");
document.writeln("						<ul class=\'e_nav\'>");
document.writeln("							<li><a href=\'jtjj.html\' target=\'_top\'>集团简介</a></li>");
document.writeln("							<li><a href=\'jtwh.html\' target=\'_top\'>集团文化</a></li>");
document.writeln("						</ul>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	</div>");
document.writeln("</body>");
document.writeln("</html>");